apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-k8s

resources:
  - ../../base

images:
  - name: fastapi-app
    newName: 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app
    newTag: latest

configMapGenerator:
  - name: fastapi-app-config
    envs:
      - generated-config.env
    literals:
      - PROJECT_NAME=test-k8s
      - ENVIRONMENT=prod
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - FILE_SERVICE_URL=http://file-service
      - AWS_REGION=eu-west-1
      - FIRST_SUPERUSER=admin@example.com
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: fastapi-app-secrets
    envs:
      - secrets.env
    options:
      disableNameSuffixHash: true

patches:
  - path: ingress-patch.yaml
  - path: replicas-patch.yaml
  - path: irsa-patch.yaml
