apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-app.fullname" . }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fastapi-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fastapi-app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fastapi-app.serviceAccountName" . }}
      containers:
        - name: fastapi-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "fastapi-app.fullname" . }}-config
            - secretRef:
                name: {{ include "fastapi-app.fullname" . }}-secrets
            {{- if .Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ include "fastapi-app.fullname" . }}-ssm
            {{- end }}
          readinessProbe:
            httpGet:
              path: /api/v1/utils/health-check/
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/utils/health-check/
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
