{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fastapi-app.fullname" . }}-ssm
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "fastapi-app.fullname" . }}-ssm
    creationPolicy: Owner
  data:
    - secretKey: AWS_SECRET_ARN
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/aurora_master_user_secret_arn
    - secretKey: COGNITO_CLIENT_ID
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/cognito_client_id
    - secretKey: COGNITO_ISSUER
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/cognito_issuer
    - secretKey: COGNITO_DOMAIN
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/cognito_domain
{{- end }}
