{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fastapi-app.fullname" . }}-ssm
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "fastapi-app.fullname" . }}-ssm
    creationPolicy: Owner
  data:
    - secretKey: AWS_SECRET_ARN
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/aurora_master_user_secret_arn
    - secretKey: COGNITO_CLIENT_ID
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/cognito_client_id
    - secretKey: COGNITO_ISSUER
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/cognito_issuer
    - secretKey: COGNITO_DOMAIN
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/cognito_domain
    - secretKey: POSTGRES_SERVER
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/aurora_cluster_endpoint
    - secretKey: FRONTEND_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/site_url
    - secretKey: MEDIA_QUEUE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/media_queue_url
    - secretKey: MEDIA_WORKER_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/media_worker_secret
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/api_secret_key
    - secretKey: FIRST_SUPERUSER_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/first_superuser_password
    - secretKey: REDIS_URL
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/redis_url
{{- end }}
