{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "fastapi-app.fullname" . }}-ssm
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.config.AWS_REGION | default "eu-west-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "fastapi-app.serviceAccountName" . }}
{{- end }}
